CREATE DATABASE QUANLYNHACUNGCAP;

CREATE TABLE NHACUNGCAP
(
MaNhaCC VARCHAR(10) PRIMARY KEY,
TenNhaCC VARCHAR(100),
DiaChi VARCHAR(50),
SoDT VARCHAR(20),
MaSoThue INT
);

CREATE TABLE LOAIDICHVU 
(
MaLoaiDV VARCHAR(10) PRIMARY KEY,
TenLoaiDV VARCHAR(100)
);

CREATE TABLE MUCPHI 
(
MaMP VARCHAR(10) PRIMARY KEY,
DonGia INT,
MoTa VARCHAR(50)
);

CREATE TABLE DONGXE 
(
DongXe VARCHAR(20) PRIMARY KEY,
HangXe VARCHAR(10),
SoChoNgoi INT
);

CREATE TABLE DANGKYCUNGCAP 
(
MaDKCC VARCHAR(10) PRIMARY KEY,
MaNhaCC VARCHAR(10),
MaLoaiDV VARCHAR(10),
DongXe VARCHAR(20),
MaMP VARCHAR(10),
NgayBatDauCungCap DATE,
NgayKetThucCungCap DATE,
SoLuongXeDangKy INT,
);

ALTER TABLE DANGKYCUNGCAP ADD CONSTRAINT fk_MNCC FOREIGN KEY (MaNhaCC) REFERENCES NHACUNGCAP(MaNhaCC);
ALTER TABLE DANGKYCUNGCAP ADD CONSTRAINT fk_MLDV FOREIGN KEY (MaLoaiDV) REFERENCES LOAIDICHVU(MaLoaiDV);
ALTER TABLE DANGKYCUNGCAP ADD CONSTRAINT fk_MMP FOREIGN KEY (MaMP) REFERENCES MUCPHI(MaMP);
ALTER TABLE DANGKYCUNGCAP ADD CONSTRAINT fk_DX FOREIGN KEY (DongXe) REFERENCES DONGXE(DongXe);